#!/bin/bash

DOCKER_ORIG="/usr/bin/docker-runc.orig"
WDM_NOTIF_SOCK="/run/wdm/notif"


docker_out=$("$DOCKER_ORIG" "$@")
docker_ret=$?


if [ $docker_ret -eq 0 ]; then
    # a "local:" address for netcat means a UNIX socket
    # DO NOT USE UDP (even with a corresponding server I mean): netcat does not
    # close the connection and blocks; only TCP will work as expected
    case "$1" in
        pause) echo '{"action": "pause", "container": "'"$2"'"}' | nc local:"$WDM_NOTIF_SOCK";;
        resume) echo '{"action": "resume", "container": "'"$2"'"}' | nc local:"$WDM_NOTIF_SOCK";;
    esac
fi


echo "$docker_out"
exit $docker_ret

